import psycopg2

# ORM model field definitions (field_name -> field_type_info)
# Format: (field_name, sql_type, nullable, default)

models = {
    "mes_material": [
        ("product_id", "INTEGER", True, None),
        ("material_code", "VARCHAR(100)", False, None),
        ("material_name", "VARCHAR(255)", False, None),
        ("material_type", "VARCHAR(50)", False, None),
        ("unit", "VARCHAR(20)", False, None),
        ("specification", "VARCHAR(255)", True, None),
        ("drawing_code", "VARCHAR(100)", True, None),
        ("drawing_url", "VARCHAR(500)", True, None),
        ("description", "TEXT", True, None),
        ("is_active", "BOOLEAN", False, "TRUE"),
        ("uom_category", "VARCHAR(50)", True, None),
        ("uom_code", "VARCHAR(20)", True, None),
        ("uom_name", "VARCHAR(50)", True, None),
        ("conversion_factor", "DECIMAL(12,4)", True, None),
        ("safety_stock", "DECIMAL(15,6)", True, None),
        ("lead_time", "INTEGER", True, None),
        ("procurement_type", "VARCHAR(20)", True, None),
        ("lot_size", "DECIMAL(15,6)", True, None),
        ("min_order_qty", "DECIMAL(15,6)", True, None),
        ("max_order_qty", "DECIMAL(15,6)", True, None),
        ("batch_management", "BOOLEAN", True, None),
        ("shelf_life_days", "INTEGER", True, None),
    ],
    "mes_bom_version": [
        ("product_id", "INTEGER", True, None),
        ("product_code", "VARCHAR(100)", False, None),
        ("product_name", "VARCHAR(255)", False, None),
        ("version", "VARCHAR(20)", False, None),
        ("status", "VARCHAR(20)", False, "'draft'"),
        ("description", "TEXT", True, None),
        ("ecn_code", "VARCHAR(100)", True, None),
        ("effective_date", "DATE", True, None),
    ],
    "mes_bom": [
        ("product_id", "INTEGER", True, None),
        ("product_code", "VARCHAR(100)", False, None),
        ("product_name", "VARCHAR(255)", False, None),
        ("version", "VARCHAR(20)", False, "'V1.0'"),
        ("level", "INTEGER", False, "1"),
        ("parent_item_code", "VARCHAR(100)", True, None),
        ("item_id", "INTEGER", True, None),
        ("item_code", "VARCHAR(100)", False, None),
        ("item_name", "VARCHAR(255)", False, None),
        ("quantity", "DECIMAL(15,6)", False, None),
        ("unit", "VARCHAR(20)", False, None),
        ("scrap_rate", "DECIMAL(5,4)", False, "0"),
        ("drawing_code", "VARCHAR(100)", True, None),
        ("drawing_url", "VARCHAR(500)", True, None),
        ("remark", "TEXT", True, None),
        ("is_active", "BOOLEAN", False, "TRUE"),
    ],
    "mes_work_center": [
        ("work_center_code", "VARCHAR(100)", False, None),
        ("work_center_name", "VARCHAR(255)", False, None),
        ("department", "VARCHAR(100)", True, None),
        ("location", "VARCHAR(255)", True, None),
        ("capacity", "INTEGER", False, "1"),
        ("description", "TEXT", True, None),
        ("is_active", "BOOLEAN", False, "TRUE"),
    ],
    "mes_process": [
        ("process_code", "VARCHAR(100)", False, None),
        ("process_name", "VARCHAR(255)", False, None),
        ("process_type", "VARCHAR(50)", False, None),
        ("sequence", "INTEGER", False, "0"),
        ("work_center_code", "VARCHAR(100)", True, None),
        ("work_center_name", "VARCHAR(255)", True, None),
        ("standard_time", "DECIMAL(10,2)", True, None),
        ("drawing_code", "VARCHAR(100)", True, None),
        ("description", "TEXT", True, None),
        ("is_active", "BOOLEAN", False, "TRUE"),
    ],
    "mes_route": [
        ("route_code", "VARCHAR(100)", False, None),
        ("route_name", "VARCHAR(255)", False, None),
        ("product_code", "VARCHAR(100)", False, None),
        ("product_name", "VARCHAR(255)", False, None),
        ("bom_code", "VARCHAR(100)", True, None),
        ("bom_version", "VARCHAR(20)", True, None),
        ("version", "VARCHAR(20)", False, "'V1.0'"),
        ("description", "TEXT", True, None),
        ("is_active", "BOOLEAN", False, "TRUE"),
    ],
    "mes_route_process": [
        ("route_code", "VARCHAR(100)", False, None),
        ("process_code", "VARCHAR(100)", False, None),
        ("process_name", "VARCHAR(255)", False, None),
        ("sequence", "INTEGER", False, "0"),
        ("work_center_code", "VARCHAR(100)", True, None),
        ("work_center_name", "VARCHAR(255)", True, None),
    ],
    "mes_manufacturing_order": [
        ("mo_code", "VARCHAR(100)", False, None),
        ("product_code", "VARCHAR(100)", False, None),
        ("product_name", "VARCHAR(255)", False, None),
        ("quantity", "INTEGER", False, None),
        ("actual_quantity", "INTEGER", False, "0"),
        ("status", "VARCHAR(20)", False, "'planned'"),
        ("priority", "VARCHAR(20)", False, "'normal'"),
        ("route_code", "VARCHAR(100)", True, None),
        ("bom_version", "VARCHAR(20)", True, None),
        ("planned_start_date", "TIMESTAMPTZ", True, None),
        ("planned_end_date", "TIMESTAMPTZ", True, None),
        ("actual_start_date", "TIMESTAMPTZ", True, None),
        ("actual_end_date", "TIMESTAMPTZ", True, None),
        ("source_mps_id", "INTEGER", True, None),
        ("source_mps_code", "VARCHAR(100)", True, None),
        ("source_mps_line_id", "INTEGER", True, None),
        ("source_planned_order_code", "VARCHAR(100)", True, None),
        ("warehouse_code", "VARCHAR(100)", True, None),
        ("barcode", "VARCHAR(100)", True, None),
        ("remark", "TEXT", True, None),
    ],
    "mes_work_order": [
        ("wo_code", "VARCHAR(100)", False, None),
        ("mo_code", "VARCHAR(100)", False, None),
        ("mo_name", "VARCHAR(255)", True, None),
        ("product_code", "VARCHAR(100)", False, None),
        ("product_name", "VARCHAR(255)", False, None),
        ("process_code", "VARCHAR(100)", False, None),
        ("process_name", "VARCHAR(255)", False, None),
        ("work_center_code", "VARCHAR(100)", False, None),
        ("work_center_name", "VARCHAR(255)", False, None),
        ("quantity", "INTEGER", False, None),
        ("actual_quantity", "INTEGER", False, "0"),
        ("scrap_quantity", "INTEGER", False, "0"),
        ("status", "VARCHAR(20)", False, "'pending'"),
        ("operator", "VARCHAR(100)", True, None),
        ("equipment_code", "VARCHAR(100)", True, None),
        ("shift_code", "VARCHAR(100)", True, None),
        ("batch_no", "VARCHAR(100)", True, None),
        ("barcode", "VARCHAR(100)", True, None),
        ("suspend_reason", "VARCHAR(50)", True, None),
        ("suspend_source", "VARCHAR(100)", True, None),
        ("suspended_at", "TIMESTAMPTZ", True, None),
        ("planned_start_date", "TIMESTAMPTZ", True, None),
        ("planned_end_date", "TIMESTAMPTZ", True, None),
        ("actual_start_date", "TIMESTAMPTZ", True, None),
        ("actual_end_date", "TIMESTAMPTZ", True, None),
        ("remark", "TEXT", True, None),
    ],
    "mes_production_report": [
        ("report_code", "VARCHAR(100)", False, None),
        ("wo_code", "VARCHAR(100)", False, None),
        ("mo_code", "VARCHAR(100)", False, None),
        ("process_code", "VARCHAR(100)", False, None),
        ("work_center_code", "VARCHAR(100)", False, None),
        ("operator", "VARCHAR(100)", False, None),
        ("shift_code", "VARCHAR(100)", False, None),
        ("equipment_code", "VARCHAR(100)", False, None),
        ("batch_no", "VARCHAR(100)", False, None),
        ("qualified_quantity", "INTEGER", False, None),
        ("scrap_quantity", "INTEGER", False, "0"),
        ("actual_start_time", "TIMESTAMPTZ", False, None),
        ("actual_end_time", "TIMESTAMPTZ", False, None),
        ("actual_work_hours", "FLOAT", False, "0"),
        ("remark", "TEXT", True, None),
    ],
    "mes_material_requisition": [
        ("requisition_code", "VARCHAR(100)", False, None),
        ("mo_code", "VARCHAR(100)", False, None),
        ("requisition_type", "VARCHAR(20)", False, "'auto'"),
        ("status", "VARCHAR(20)", False, "'draft'"),
        ("warehouse_code", "VARCHAR(100)", False, None),
        ("location_code", "VARCHAR(100)", False, None),
        ("applicant", "VARCHAR(100)", False, None),
        ("remark", "TEXT", True, None),
    ],
    "mes_material_requisition_detail": [
        ("requisition_id", "INTEGER", False, None),
        ("material_code", "VARCHAR(100)", False, None),
        ("material_name", "VARCHAR(255)", False, None),
        ("required_quantity", "DECIMAL(15,6)", False, None),
        ("issued_quantity", "DECIMAL(15,6)", False, "0"),
        ("unit", "VARCHAR(20)", False, None),
        ("process_code", "VARCHAR(100)", True, None),
        ("substitute_material_code", "VARCHAR(100)", True, None),
        ("is_substituted", "BOOLEAN", False, "FALSE"),
    ],
    "mes_material_return": [
        ("return_code", "VARCHAR(100)", False, None),
        ("mo_code", "VARCHAR(100)", False, None),
        ("requisition_code", "VARCHAR(100)", False, None),
        ("status", "VARCHAR(20)", False, "'draft'"),
        ("warehouse_code", "VARCHAR(100)", False, None),
        ("location_code", "VARCHAR(100)", False, None),
        ("operator", "VARCHAR(100)", False, None),
        ("remark", "TEXT", True, None),
    ],
    "mes_production_receipt": [
        ("receipt_code", "VARCHAR(100)", False, None),
        ("mo_code", "VARCHAR(100)", False, None),
        ("product_code", "VARCHAR(100)", False, None),
        ("product_name", "VARCHAR(255)", False, None),
        ("batch_no", "VARCHAR(100)", False, None),
        ("quantity", "INTEGER", False, None),
        ("unit", "VARCHAR(20)", False, None),
        ("warehouse_code", "VARCHAR(100)", False, None),
        ("location_code", "VARCHAR(100)", False, None),
        ("inspection_result", "VARCHAR(20)", False, None),
        ("status", "VARCHAR(20)", False, "'draft'"),
        ("remark", "TEXT", True, None),
    ],
    "mes_production_exception": [
        ("exception_code", "VARCHAR(100)", False, None),
        ("exception_type", "VARCHAR(20)", False, None),
        ("severity", "VARCHAR(20)", False, "'minor'"),
        ("wo_code", "VARCHAR(100)", True, None),
        ("mo_code", "VARCHAR(100)", True, None),
        ("work_center_code", "VARCHAR(100)", False, None),
        ("description", "TEXT", False, None),
        ("reporter", "VARCHAR(100)", False, None),
        ("status", "VARCHAR(20)", False, "'reported'"),
        ("handler", "VARCHAR(100)", True, None),
        ("solution", "TEXT", True, None),
        ("resolved_at", "TIMESTAMPTZ", True, None),
        ("escalation_level", "INTEGER", False, "0"),
    ],
    "mes_shift_definition": [
        ("shift_code", "VARCHAR(20)", False, None),
        ("shift_name", "VARCHAR(50)", False, None),
        ("start_time", "VARCHAR(5)", False, None),
        ("end_time", "VARCHAR(5)", False, None),
        ("work_center_code", "VARCHAR(100)", True, None),
        ("is_active", "BOOLEAN", False, "TRUE"),
        ("description", "TEXT", True, None),
    ],
    "mes_shift_schedule": [
        ("shift_code", "VARCHAR(20)", False, None),
        ("work_center_code", "VARCHAR(100)", False, None),
        ("date", "DATE", False, None),
        ("operator_list", "JSONB", False, None),
        ("leader", "VARCHAR(100)", False, None),
    ],
    "mes_shift_handover": [
        ("shift_code", "VARCHAR(20)", False, None),
        ("work_center_code", "VARCHAR(100)", False, None),
        ("date", "DATE", False, None),
        ("outgoing_leader", "VARCHAR(100)", False, None),
        ("incoming_leader", "VARCHAR(100)", False, None),
        ("equipment_status", "TEXT", False, None),
        ("production_progress", "TEXT", False, None),
        ("exception_items", "TEXT", False, None),
        ("remark", "TEXT", True, None),
    ],
    "mes_trace_record": [
        ("trace_code", "VARCHAR(100)", False, None),
        ("product_batch_no", "VARCHAR(100)", False, None),
        ("material_batch_no", "VARCHAR(100)", False, None),
        ("mo_code", "VARCHAR(100)", False, None),
        ("wo_code", "VARCHAR(100)", False, None),
        ("process_code", "VARCHAR(100)", False, None),
        ("operator", "VARCHAR(100)", False, None),
        ("equipment_code", "VARCHAR(100)", False, None),
        ("work_center_code", "VARCHAR(100)", False, None),
        ("shift_code", "VARCHAR(100)", False, None),
        ("consumed_quantity", "DECIMAL(15,6)", False, None),
        ("produced_quantity", "INTEGER", False, "0"),
    ],
    "mes_tooling": [
        ("tooling_code", "VARCHAR(100)", False, None),
        ("tooling_name", "VARCHAR(255)", False, None),
        ("tooling_type", "VARCHAR(20)", False, None),
        ("status", "VARCHAR(20)", False, "'available'"),
        ("life_count", "INTEGER", True, None),
        ("used_count", "INTEGER", False, "0"),
        ("life_hours", "FLOAT", True, None),
        ("used_hours", "FLOAT", False, "0"),
        ("calibration_date", "DATE", True, None),
        ("next_calibration_date", "DATE", True, None),
        ("work_center_code", "VARCHAR(100)", True, None),
        ("is_active", "BOOLEAN", False, "TRUE"),
    ],
    "mes_tooling_process_binding": [
        ("tooling_code", "VARCHAR(100)", False, None),
        ("process_code", "VARCHAR(100)", False, None),
    ],
    "mes_energy_record": [
        ("equipment_code", "VARCHAR(100)", False, None),
        ("energy_type", "VARCHAR(20)", False, None),
        ("consumption_value", "DECIMAL(15,6)", False, None),
        ("unit", "VARCHAR(20)", False, None),
        ("record_time", "TIMESTAMPTZ", False, None),
        ("work_center_code", "VARCHAR(100)", False, None),
        ("shift_code", "VARCHAR(100)", True, None),
    ],
    "mes_barcode_record": [
        ("barcode", "VARCHAR(100)", False, None),
        ("barcode_type", "VARCHAR(20)", False, None),
        ("reference_code", "VARCHAR(100)", False, None),
        ("is_active", "BOOLEAN", False, "TRUE"),
    ],
    "mes_operation_log": [
        ("entity_type", "VARCHAR(50)", False, None),
        ("entity_id", "INTEGER", False, None),
        ("action", "VARCHAR(50)", False, None),
        ("old_value", "JSONB", True, None),
        ("new_value", "JSONB", True, None),
        ("operator", "VARCHAR(100)", False, None),
        ("operated_at", "TIMESTAMPTZ", False, None),
        ("remark", "TEXT", True, None),
    ],
    "mrp2_sales_forecast": [
        ("forecast_code", "VARCHAR(100)", False, None),
        ("forecast_name", "VARCHAR(255)", False, None),
        ("forecast_type", "VARCHAR(20)", False, "'monthly'"),
        ("forecast_date", "DATE", False, None),
        ("start_date", "DATE", False, None),
        ("end_date", "DATE", False, None),
        ("status", "VARCHAR(20)", False, "'draft'"),
        ("source", "VARCHAR(50)", False, "'manual'"),
        ("description", "TEXT", True, None),
        ("created_by", "VARCHAR(100)", True, None),
    ],
    "mrp2_sales_forecast_detail": [
        ("forecast_id", "INTEGER", False, None),
        ("forecast_code", "VARCHAR(100)", False, None),
        ("product_id", "INTEGER", True, None),
        ("product_code", "VARCHAR(100)", False, None),
        ("product_name", "VARCHAR(255)", False, None),
        ("period_type", "VARCHAR(20)", False, "'month'"),
        ("period_start", "DATE", False, None),
        ("period_end", "DATE", False, None),
        ("forecast_quantity", "DECIMAL(15,6)", False, None),
        ("unit", "VARCHAR(20)", False, None),
        ("confidence", "DECIMAL(5,2)", False, "80"),
        ("remark", "TEXT", True, None),
    ],
    "mrp2_master_production_schedule": [
        ("mps_code", "VARCHAR(100)", False, None),
        ("mps_name", "VARCHAR(255)", False, None),
        ("start_date", "DATE", False, None),
        ("end_date", "DATE", False, None),
        ("period_type", "VARCHAR(20)", False, "'week'"),
        ("status", "VARCHAR(20)", False, "'draft'"),
        ("forecast_id", "INTEGER", True, None),
        ("forecast_code", "VARCHAR(100)", True, None),
        ("plan_name", "VARCHAR(255)", True, None),
        ("approved_by", "VARCHAR(100)", True, None),
        ("approved_at", "TIMESTAMPTZ", True, None),
        ("released_by", "VARCHAR(100)", True, None),
        ("released_at", "TIMESTAMPTZ", True, None),
        ("demand_time_fence", "INTEGER", False, "7"),
        ("planning_time_fence", "INTEGER", False, "14"),
        ("description", "TEXT", True, None),
        ("created_by", "VARCHAR(100)", True, None),
    ],
    "mrp2_mps_detail": [
        ("mps_id", "INTEGER", False, None),
        ("mps_code", "VARCHAR(100)", False, None),
        ("product_id", "INTEGER", True, None),
        ("product_code", "VARCHAR(100)", False, None),
        ("product_name", "VARCHAR(255)", False, None),
        ("bom_version", "VARCHAR(20)", True, None),
        ("route_code", "VARCHAR(100)", True, None),
        ("period_start", "DATE", False, None),
        ("period_end", "DATE", False, None),
        ("forecast_quantity", "DECIMAL(15,6)", False, "0"),
        ("planned_quantity", "DECIMAL(15,6)", False, None),
        ("production_quantity", "DECIMAL(15,6)", False, "0"),
        ("unit", "VARCHAR(20)", False, None),
        ("safety_stock", "DECIMAL(15,6)", False, "0"),
        ("planned_inventory", "DECIMAL(15,6)", False, "0"),
        ("remark", "TEXT", True, None),
    ],
    "mrp2_mps_plan_line": [
        ("mps_id", "INTEGER", False, None),
        ("mps_code", "VARCHAR(100)", False, None),
        ("line_no", "INTEGER", False, None),
        ("product_code", "VARCHAR(100)", False, None),
        ("product_name", "VARCHAR(255)", False, None),
        ("plan_quantity", "DECIMAL(15,6)", False, None),
        ("plan_start_date", "DATE", False, None),
        ("plan_end_date", "DATE", False, None),
        ("priority", "INTEGER", False, "5"),
        ("sales_order_no", "VARCHAR(100)", True, None),
        ("sales_order_line_no", "INTEGER", True, None),
        ("bom_code", "VARCHAR(100)", True, None),
        ("route_code", "VARCHAR(100)", True, None),
        ("capacity_check_result", "VARCHAR(20)", False, "'pass'"),
        ("capacity_check_remark", "TEXT", True, None),
        ("actual_quantity", "DECIMAL(15,6)", False, "0"),
        ("status", "VARCHAR(20)", False, "'planned'"),
        ("remark", "TEXT", True, None),
    ],
    "mrp2_mrp_calculation": [
        ("mrp_code", "VARCHAR(100)", False, None),
        ("mrp_name", "VARCHAR(255)", False, None),
        ("mps_id", "INTEGER", True, None),
        ("mps_code", "VARCHAR(100)", True, None),
        ("calculation_date", "TIMESTAMPTZ", False, None),
        ("status", "VARCHAR(20)", False, "'calculating'"),
        ("start_date", "DATE", False, None),
        ("end_date", "DATE", False, None),
        ("net_requirement_only", "BOOLEAN", False, "FALSE"),
        ("include_safety_stock", "BOOLEAN", False, "TRUE"),
        ("include_wip", "BOOLEAN", False, "TRUE"),
        ("calculation_result", "JSONB", True, None),
        ("error_message", "TEXT", True, None),
        ("created_by", "VARCHAR(100)", True, None),
    ],
    "mrp2_mrp_result_detail": [
        ("mrp_id", "INTEGER", False, None),
        ("mrp_code", "VARCHAR(100)", False, None),
        ("level", "INTEGER", False, "1"),
        ("product_id", "INTEGER", True, None),
        ("product_code", "VARCHAR(100)", False, None),
        ("product_name", "VARCHAR(255)", False, None),
        ("period_start", "DATE", False, None),
        ("period_end", "DATE", False, None),
        ("gross_requirement", "DECIMAL(15,6)", False, "0"),
        ("scheduled_receipts", "DECIMAL(15,6)", False, "0"),
        ("projected_available", "DECIMAL(15,6)", False, "0"),
        ("net_requirement", "DECIMAL(15,6)", False, "0"),
        ("planned_order_receipt", "DECIMAL(15,6)", False, "0"),
        ("planned_order_release", "DECIMAL(15,6)", False, "0"),
        ("planned_release_date", "DATE", True, None),
        ("planned_receipt_date", "DATE", True, None),
        ("lot_size", "DECIMAL(15,6)", False, "1"),
        ("lead_time", "INTEGER", False, "0"),
        ("safety_stock", "DECIMAL(15,6)", False, "0"),
        ("unit", "VARCHAR(20)", False, None),
        ("parent_item_code", "VARCHAR(100)", True, None),
        ("bom_quantity", "DECIMAL(15,6)", False, "1"),
    ],
    "mrp2_capacity_requirement_plan": [
        ("crp_code", "VARCHAR(100)", False, None),
        ("crp_name", "VARCHAR(255)", False, None),
        ("mrp_id", "INTEGER", True, None),
        ("mrp_code", "VARCHAR(100)", True, None),
        ("mps_id", "INTEGER", True, None),
        ("mps_code", "VARCHAR(100)", True, None),
        ("status", "VARCHAR(20)", False, "'calculating'"),
        ("start_date", "DATE", False, None),
        ("end_date", "DATE", False, None),
        ("calculation_date", "TIMESTAMPTZ", False, None),
        ("overall_capacity_utilization", "DECIMAL(5,2)", False, "0"),
        ("bottleneck_work_centers", "JSONB", True, None),
        ("calculation_summary", "JSONB", True, None),
        ("error_message", "TEXT", True, None),
        ("created_by", "VARCHAR(100)", True, None),
    ],
    "mrp2_crp_detail": [
        ("crp_id", "INTEGER", False, None),
        ("crp_code", "VARCHAR(100)", False, None),
        ("work_center_code", "VARCHAR(100)", False, None),
        ("work_center_name", "VARCHAR(255)", False, None),
        ("period_start", "DATE", False, None),
        ("period_end", "DATE", False, None),
        ("available_capacity", "DECIMAL(15,2)", False, None),
        ("required_capacity", "DECIMAL(15,2)", False, None),
        ("utilized_capacity", "DECIMAL(15,2)", False, "0"),
        ("capacity_utilization", "DECIMAL(5,2)", False, "0"),
        ("is_overloaded", "BOOLEAN", False, "FALSE"),
        ("overload_hours", "DECIMAL(15,2)", False, "0"),
        ("recommended_action", "TEXT", True, None),
        ("detail_items", "JSONB", True, None),
    ],
    "mrp2_plan_execution_monitor": [
        ("monitor_code", "VARCHAR(100)", False, None),
        ("monitor_name", "VARCHAR(255)", False, None),
        ("mps_id", "INTEGER", True, None),
        ("mps_code", "VARCHAR(100)", True, None),
        ("mrp_id", "INTEGER", True, None),
        ("mrp_code", "VARCHAR(100)", True, None),
        ("start_date", "DATE", False, None),
        ("end_date", "DATE", False, None),
        ("status", "VARCHAR(20)", False, "'monitoring'"),
        ("overall_progress", "DECIMAL(5,2)", False, "0"),
        ("on_time_rate", "DECIMAL(5,2)", False, "0"),
        ("quality_rate", "DECIMAL(5,2)", False, "0"),
        ("efficiency_rate", "DECIMAL(5,2)", False, "0"),
        ("alert_count", "INTEGER", False, "0"),
        ("exception_count", "INTEGER", False, "0"),
        ("metrics_summary", "JSONB", True, None),
        ("created_by", "VARCHAR(100)", True, None),
    ],
    "mrp2_exception_alert": [
        ("alert_code", "VARCHAR(100)", False, None),
        ("monitor_id", "INTEGER", True, None),
        ("alert_type", "VARCHAR(50)", False, None),
        ("alert_level", "VARCHAR(20)", False, "'warning'"),
        ("alert_status", "VARCHAR(20)", False, "'active'"),
        ("related_code", "VARCHAR(100)", True, None),
        ("related_name", "VARCHAR(255)", True, None),
        ("description", "TEXT", False, None),
        ("recommended_action", "TEXT", True, None),
        ("resolved_by", "VARCHAR(100)", True, None),
        ("resolved_at", "TIMESTAMPTZ", True, None),
        ("resolved_note", "TEXT", True, None),
    ],
    "mrp2_planned_order": [
        ("order_code", "VARCHAR(100)", False, None),
        ("mrp_id", "INTEGER", True, None),
        ("mrp_code", "VARCHAR(100)", True, None),
        ("order_type", "VARCHAR(20)", False, None),
        ("material_code", "VARCHAR(100)", False, None),
        ("material_name", "VARCHAR(255)", False, None),
        ("net_quantity", "DECIMAL(15,6)", False, None),
        ("plan_quantity", "DECIMAL(15,6)", False, None),
        ("unit", "VARCHAR(20)", False, None),
        ("require_date", "DATE", False, None),
        ("plan_release_date", "DATE", True, None),
        ("lead_time", "INTEGER", False, "0"),
        ("batch_rule", "VARCHAR(20)", False, "'lot_for_lot'"),
        ("batch_size", "DECIMAL(15,6)", False, "1"),
        ("safety_stock", "DECIMAL(15,6)", False, "0"),
        ("current_stock", "DECIMAL(15,6)", False, "0"),
        ("on_order_quantity", "DECIMAL(15,6)", False, "0"),
        ("gross_requirement", "DECIMAL(15,6)", False, "0"),
        ("net_requirement", "DECIMAL(15,6)", False, "0"),
        ("bom_level", "INTEGER", False, "0"),
        ("parent_material_code", "VARCHAR(100)", True, None),
        ("status", "VARCHAR(20)", False, "'planned'"),
        ("source_mps_id", "INTEGER", True, None),
        ("source_mps_line_id", "INTEGER", True, None),
        ("converted_mo_code", "VARCHAR(100)", True, None),
        ("remark", "TEXT", True, None),
    ],
    "product": [
        ("name", "VARCHAR(255)", False, None),
        ("description", "TEXT", True, None),
        ("price", "DECIMAL(10,2)", False, None),
        ("original_price", "DECIMAL(10,2)", True, None),
        ("sale_price", "DECIMAL(10,2)", True, None),
        ("stock", "INTEGER", False, "0"),
        ("sort", "INTEGER", False, "0"),
        ("category", "VARCHAR(50)", True, None),
        ("tags", "JSONB", True, None),
        ("images", "JSONB", True, None),
        ("is_active", "BOOLEAN", False, "TRUE"),
        ("is_hot", "BOOLEAN", False, "FALSE"),
        ("is_new", "BOOLEAN", False, "FALSE"),
        ("view_count", "INTEGER", False, "0"),
        ("sales_count", "INTEGER", False, "0"),
        ("uom_id", "INTEGER", True, None),
        ("uom_code", "VARCHAR(20)", False, "'unit'"),
        ("uom_name", "VARCHAR(50)", False, "'件'"),
        ("uom_category", "VARCHAR(50)", False, "'unit'"),
        ("secondary_uom_id", "INTEGER", True, None),
        ("secondary_uom_code", "VARCHAR(20)", True, None),
        ("secondary_uom_name", "VARCHAR(50)", True, None),
        ("conversion_factor", "DECIMAL(12,4)", False, "1"),
        ("recharge_hours", "INTEGER", True, None),
        ("bonus_hours", "INTEGER", False, "0"),
        ("discount_description", "VARCHAR(255)", True, None),
        ("membership_level_id", "INTEGER", True, None),
        ("product_type", "VARCHAR(50)", False, "'item'"),
        ("price_mode", "VARCHAR(20)", False, "'dynamic'"),
    ],
}

# DB columns from the query
db_columns = {
    "mes_material": ["id", "created_at", "updated_at", "product_id", "material_code", "material_name", "material_type", "unit", "specification", "description", "is_active", "drawing_url", "drawing_code", "conversion_factor", "uom_category", "uom_code", "uom_name", "safety_stock", "lead_time", "procurement_type", "lot_size", "min_order_qty", "max_order_qty", "batch_management", "shelf_life_days"],
    "mes_bom_version": ["id", "created_at", "updated_at", "product_id", "product_code", "product_name", "version", "status", "description", "ecn_code", "effective_date"],
    "mes_bom": ["id", "created_at", "updated_at", "product_id", "product_code", "product_name", "version", "level", "parent_item_code", "item_id", "item_code", "item_name", "quantity", "unit", "scrap_rate", "remark", "is_active", "drawing_url", "drawing_code"],
    "mes_work_center": ["id", "created_at", "updated_at", "work_center_code", "work_center_name", "department", "location", "capacity", "description", "is_active"],
    "mes_process": ["id", "created_at", "updated_at", "process_code", "process_name", "process_type", "sequence", "work_center_code", "work_center_name", "standard_time", "description", "is_active", "drawing_code"],
    "mes_route": ["id", "created_at", "updated_at", "route_code", "route_name", "product_code", "product_name", "version", "description", "is_active", "bom_code", "bom_version"],
    "mes_route_process": ["id", "created_at", "updated_at", "route_code", "process_code", "process_name", "sequence", "work_center_code", "work_center_name"],
    "mes_manufacturing_order": ["id", "created_at", "updated_at", "mo_code", "product_code", "product_name", "quantity", "actual_quantity", "status", "priority", "route_code", "bom_version", "planned_start_date", "planned_end_date", "actual_start_date", "actual_end_date", "remark", "source_type", "source_code", "released_at", "source_mps_id", "source_mps_code", "source_mps_line_id", "source_planned_order_code", "warehouse_code", "barcode"],
    "mes_work_order": ["id", "created_at", "updated_at", "wo_code", "mo_code", "mo_name", "product_code", "product_name", "process_code", "process_name", "work_center_code", "work_center_name", "quantity", "actual_quantity", "scrap_quantity", "status", "operator", "planned_start_date", "planned_end_date", "actual_start_date", "actual_end_date", "remark", "equipment_code", "shift_code", "batch_no", "actual_work_hours", "suspended_at", "suspend_reason", "resumed_at", "barcode", "suspend_source"],
    "mes_production_report": ["id", "report_code", "wo_code", "mo_code", "process_code", "work_center_code", "equipment_code", "shift_code", "batch_no", "operator", "qualified_quantity", "scrap_quantity", "actual_work_hours", "actual_start_time", "actual_end_time", "remark", "created_at", "updated_at"],
    "mes_material_requisition": ["id", "requisition_code", "mo_code", "requisition_type", "warehouse_code", "location_code", "applicant", "status", "remark", "created_at", "updated_at"],
    "mes_material_requisition_detail": ["id", "requisition_id", "material_code", "material_name", "required_quantity", "issued_quantity", "unit", "warehouse_code", "location_code", "batch_no", "remark", "created_at", "updated_at", "process_code", "substitute_material_code", "is_substituted"],
    "mes_material_return": ["id", "return_code", "mo_code", "warehouse_code", "location_code", "operator", "status", "remark", "created_at", "updated_at", "requisition_code"],
    "mes_production_receipt": ["id", "receipt_code", "mo_code", "product_code", "product_name", "quantity", "unit", "batch_no", "warehouse_code", "location_code", "inspection_result", "operator", "status", "remark", "created_at", "updated_at"],
    "mes_production_exception": ["id", "exception_code", "exception_type", "severity", "wo_code", "work_center_code", "description", "reporter", "handler", "handle_measure", "handle_result", "status", "resolved_at", "remark", "created_at", "updated_at", "mo_code", "solution", "escalation_level"],
    "mes_shift_definition": ["id", "shift_code", "shift_name", "start_time", "end_time", "work_center_code", "is_cross_day", "remark", "created_at", "updated_at", "is_active", "description"],
    "mes_shift_schedule": ["id", "shift_id", "shift_code", "work_center_code", "schedule_date", "worker_id", "worker_name", "remark", "created_at", "updated_at", "date", "operator_list", "leader"],
    "mes_shift_handover": ["id", "shift_code", "work_center_code", "handover_date", "from_worker", "to_worker", "handover_content", "remark", "created_at", "updated_at", "date", "outgoing_leader", "incoming_leader", "equipment_status", "production_progress", "exception_items"],
    "mes_trace_record": ["id", "trace_type", "material_batch_no", "material_code", "material_name", "product_batch_no", "product_code", "product_name", "wo_code", "mo_code", "process_code", "work_center_code", "operator", "quantity", "remark", "created_at", "updated_at", "trace_code", "equipment_code", "shift_code", "consumed_quantity", "produced_quantity"],
    "mes_tooling": ["id", "tooling_code", "tooling_name", "tooling_type", "work_center_code", "status", "total_usage_count", "max_usage_count", "last_validated_at", "remark", "created_at", "updated_at", "life_count", "used_count", "life_hours", "used_hours", "calibration_date", "next_calibration_date", "is_active"],
    "mes_tooling_process_binding": ["id", "tooling_code", "process_code", "created_at", "updated_at"],
    "mes_energy_record": ["id", "work_center_code", "energy_type", "consumption", "unit", "record_date", "recorder", "remark", "created_at", "updated_at", "equipment_code", "consumption_value", "record_time", "shift_code"],
    "mes_barcode_record": ["id", "barcode", "barcode_type", "entity_type", "entity_code", "status", "parsed_data", "created_at", "updated_at", "reference_code", "is_active"],
    "mes_operation_log": ["id", "operation_type", "entity_type", "entity_code", "operator", "detail", "created_at", "updated_at", "entity_id", "action", "old_value", "new_value", "operated_at", "remark"],
    "mrp2_sales_forecast": ["id", "created_at", "updated_at", "forecast_code", "forecast_name", "forecast_type", "forecast_date", "start_date", "end_date", "status", "source", "description", "created_by"],
    "mrp2_sales_forecast_detail": ["id", "created_at", "updated_at", "forecast_id", "forecast_code", "product_id", "product_code", "product_name", "period_type", "period_start", "period_end", "forecast_quantity", "unit", "confidence", "remark"],
    "mrp2_master_production_schedule": ["id", "created_at", "updated_at", "mps_code", "mps_name", "start_date", "end_date", "period_type", "status", "forecast_id", "forecast_code", "description", "created_by", "plan_name", "approved_by", "approved_at", "released_by", "released_at", "demand_time_fence", "planning_time_fence"],
    "mrp2_mps_detail": ["id", "created_at", "updated_at", "mps_id", "mps_code", "product_id", "product_code", "product_name", "bom_version", "route_code", "period_start", "period_end", "forecast_quantity", "planned_quantity", "production_quantity", "unit", "safety_stock", "planned_inventory", "remark"],
    "mrp2_mps_plan_line": ["id", "mps_id", "mps_code", "line_no", "product_code", "product_name", "plan_quantity", "plan_start_date", "plan_end_date", "priority", "sales_order_no", "sales_order_line_no", "bom_code", "route_code", "capacity_check_result", "capacity_check_remark", "actual_quantity", "status", "remark", "created_at", "updated_at"],
    "mrp2_mrp_calculation": ["id", "created_at", "updated_at", "mrp_code", "mrp_name", "mps_id", "mps_code", "calculation_date", "status", "start_date", "end_date", "net_requirement_only", "include_safety_stock", "include_wip", "calculation_result", "error_message", "created_by"],
    "mrp2_mrp_result_detail": ["id", "created_at", "updated_at", "mrp_id", "mrp_code", "level", "product_id", "product_code", "product_name", "period_start", "period_end", "gross_requirement", "scheduled_receipts", "projected_available", "net_requirement", "planned_order_receipt", "planned_order_release", "planned_release_date", "planned_receipt_date", "lot_size", "lead_time", "safety_stock", "unit", "parent_item_code", "bom_quantity"],
    "mrp2_capacity_requirement_plan": ["id", "created_at", "updated_at", "crp_code", "crp_name", "mrp_id", "mrp_code", "mps_id", "mps_code", "status", "start_date", "end_date", "calculation_date", "overall_capacity_utilization", "bottleneck_work_centers", "calculation_summary", "error_message", "created_by"],
    "mrp2_crp_detail": ["id", "created_at", "updated_at", "crp_id", "crp_code", "work_center_code", "work_center_name", "period_start", "period_end", "available_capacity", "required_capacity", "utilized_capacity", "capacity_utilization", "is_overloaded", "overload_hours", "recommended_action", "detail_items"],
    "mrp2_plan_execution_monitor": ["id", "created_at", "updated_at", "monitor_code", "monitor_name", "mps_id", "mps_code", "mrp_id", "mrp_code", "start_date", "end_date", "status", "overall_progress", "on_time_rate", "quality_rate", "efficiency_rate", "alert_count", "exception_count", "metrics_summary", "created_by"],
    "mrp2_exception_alert": ["id", "created_at", "updated_at", "alert_code", "monitor_id", "alert_type", "alert_level", "alert_status", "related_code", "related_name", "description", "recommended_action", "resolved_by", "resolved_at", "resolved_note"],
    "mrp2_planned_order": ["id", "mrp_id", "mrp_code", "order_no", "order_type", "item_code", "item_name", "planned_quantity", "unit", "planned_start_date", "planned_end_date", "source_type", "source_code", "bom_code", "route_code", "status", "confirmed_quantity", "remark", "created_at", "updated_at", "order_code", "net_quantity", "plan_quantity", "material_code", "material_name", "require_date", "plan_release_date", "lead_time", "batch_rule", "batch_size", "safety_stock", "current_stock", "on_order_quantity", "gross_requirement", "net_requirement", "bom_level", "parent_material_code", "source_mps_id", "source_mps_line_id", "converted_mo_code"],
    "product": ["id", "created_at", "updated_at", "name", "description", "price", "stock", "category", "tags", "images", "is_active", "is_hot", "is_new", "view_count", "sales_count", "original_price", "sale_price", "recharge_hours", "bonus_hours", "discount_description", "sort", "membership_level_id", "product_type", "price_mode", "secondary_uom_id"],
}

# Compare and generate ALTER TABLE statements
alter_statements = []
for table, model_fields in models.items():
    db_cols = set(db_columns.get(table, []))
    model_col_names = set(f[0] for f in model_fields)
    
    missing_in_db = model_col_names - db_cols
    if missing_in_db:
        print(f"\n-- {table}: Missing columns in DB: {missing_in_db}")
        for field_name, sql_type, nullable, default in model_fields:
            if field_name in missing_in_db:
                null_str = "" if nullable else " NOT NULL"
                default_str = f" DEFAULT {default}" if default else ""
                stmt = f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {field_name} {sql_type}{null_str}{default_str};"
                alter_statements.append(stmt)
                print(f"  {stmt}")

if not alter_statements:
    print("\nNo missing columns found!")
else:
    print(f"\n\n-- Total ALTER TABLE statements: {len(alter_statements)}")
    print("-- Execute the following SQL:")
    for stmt in alter_statements:
        print(stmt)