/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApprovalAction: typeof import('./components/ApprovalAction.vue')['default']
    ApprovalFlowCanvas: typeof import('./components/approval/ApprovalFlowCanvas.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    FlowNodePanel: typeof import('./components/approval/FlowNodePanel.vue')['default']
    GlobalApproval: typeof import('./components/GlobalApproval.vue')['default']
    LangGraphEditor: typeof import('./components/LangGraphEditor.vue')['default']
    MailBell: typeof import('./components/MailBell.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
